version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
